FROM node:6

MAINTAINER Yohan Graterol <yohangraterol92@gmail.com>

RUN apt-get install wget bash git python curl

ENV DB_HOST localhost

ENV DB_USER root

ENV DB_PASSWORD password

RUN  npm install -g pkg grunt-cli

COPY mainnet/entrypoint.sh /usr/local/bin

USER node

WORKDIR /home/node/

COPY ark-to-bin.sh .

RUN ./ark-to-bin.sh

RUN cd ark

RUN mkdir logs

COPY mainnet/config.mainnet.json .

COPY mainnet/genesisBlock.mainnet.json .

EXPOSE 4001

ENTRYPOINT ["entrypoint.sh"]

CMD ["./ark/ark-node", "--genesis", "genesisBlock.mainnet.json", "--config", "config.mainnet.json"]
